### ISSUE TITLE
Divide by Zero

### ISSUE THREAD

**Issue by chancyk** [dedupeio/affinegap#4] opened 2018-01-25 23:39 UTC
The normalized function does not check that both string lengths are greater than zero. For some reason this issue is arising in my dataset despite using `has missing`. 

Is 0.0 appropriate here given that lower values are more similar in [normalizedAffineGapDistance](https://github.com/dedupeio/affinegap/blob/master/affinegap/affinegap.pyx#L120)?

**Comment by kball** [comment] 2018-02-03 00:26
I'm also running into this. The backtrace looks like this:

```
 File "/Users/kball/git/getit/listing-dedupe/deduper.py", line 78, in train
    self.deduper.readTraining(tf)
  File "/Users/kball/.virtualenvs/listing-dedupe/lib/python3.6/site-packages/dedupe/api.py", line 648, in readTraining
    self.markPairs(training_pairs)
  File "/Users/kball/.virtualenvs/listing-dedupe/lib/python3.6/site-packages/dedupe/api.py", line 730, in markPairs
    self.active_learner.mark(examples, y)
  File "/Users/kball/.virtualenvs/listing-dedupe/lib/python3.6/site-packages/dedupe/labeler.py", line 118, in mark
    self.X = numpy.vstack([self.X, self.transform(pairs)])
  File "/Users/kball/.virtualenvs/listing-dedupe/lib/python3.6/site-packages/dedupe/labeler.py", line 89, in transform
    return self.data_model.distances(pairs)
  File "/Users/kball/.virtualenvs/listing-dedupe/lib/python3.6/site-packages/dedupe/datamodel.py", line 82, in distances
    record_2[field])
  File "affinegap/affinegap.pyx", line 115, in affinegap.affinegap.normalizedAffineGapDistance (affinegap/affinegap.c:1991)
  File "affinegap/affinegap.pyx", line 134, in affinegap.affinegap.normalizedAffineGapDistance (affinegap/affinegap.c:1824)
ZeroDivisionError: float division
```

**Comment by kball** [comment] 2018-02-03 00:37
I went in to go write a PR to handle this case, and then discovered that it looks like this behavior was deliberately introduced in https://github.com/dedupeio/affinegap/commit/4dd2757e6da4515103bdc72aec0606776fc05d4d and https://github.com/dedupeio/affinegap/commit/5e189f0ddf9e0f72a8b8f7394165daa3cc83826a

@fgregg can you advise as to what expected behavior is and how we should update dedupe or our dedupe configurations to avoid this?

**Comment by fgregg** [comment] 2018-02-12 02:40
0.0 is no appropriate because, that the same value as what you get for two exact strings. 

Maybe the right things is to return `float('nan')`, but I actually think the better thing to do is to continue to raise an exception, but give a more useful error message.

**Comment by herberthamaral** [comment] 2018-04-03 02:34
Since `TextType` uses cosine distance, I am basically using `Text` instead of `String` and `ShortString` in dedupe's config.

I don't think the impact is enormous, but until this gets solved it is basically impossible to use `String` with missing values in dedupe.

FWIW, I think this should be fixed in dedupe, not in here: https://github.com/dedupeio/dedupe/issues/639

**Comment by nrajasek1** [comment] 2021-01-13 13:37
is the issues resolved? any alternate? i am getting same error when running mysql_example script with same data set. please advice

**Closed** 2022-01-01 00:00 UTC
